Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,8 +1,64 @@
-node{
-  stage('SCM Checkout'){
-    git 'https://github.com/navalbciit/my-app2'
+//node{
+  //stage('SCM Checkout'){
+    //git 'https://github.com/navalbciit/my-app2'
+    //}
+    //stage('Compile-Package'){
+    //sh 'mvn package'
+   //}
+ //}
+ pipeline {
+    agent any
+    
+    stages {
+       
+        stage('clean and clone') {
+            steps {
+                sh "rm -rf my-app2"
+                sh " git clone https://github.com/navalbciit/my-app2.git"
+                sh "mvn clean -f my-app2"
+            }
+        }
+        stage('Test') {
+            steps {
+                sh "mvn test -f my-app2"
+            }
+        }
+        stage('Deploy') {
+            steps {
+                sh "mvn package -f my-app21"
+            }
+           
+        }
+       //tage('email') {
+           //steps{
+           //mail bcc: '', body: 'test', cc: '', from: '', replyTo: '', subject: 'jenkins', to: 'sharmanaval365@gmail.com'
+      // }
+      //}
+      //stage('TEST') {  
+             //steps {  
+            //     sh 'echo "Fail!"; exit 1'  
+          //   }  
+        // }  
     }
-    stage('Compile-Package'){
-    sh 'mvn package'
-    }
- }
+     post {  
+         always {  
+             echo 'This will always run'  
+         }  
+         success {
+             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: '', mimeType: 'text/html', replyTo: '', subject: "SUCCESS CI: Project name -> ${env.JOB_NAME}", to: "sharmanaval12k4@gmail.com";
+             echo 'This will run only if successful'  
+             
+         }  
+         failure {  
+             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: '', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sharmanaval12k4@gmail.com";  
+         }  
+         unstable {  
+             echo 'This will run only if the run was marked as unstable'  
+         }  
+         changed {  
+             echo 'This will run only if the state of the Pipeline has changed'  
+             echo 'For example, if the Pipeline was previously failing but is now successful'  
+         }  
+     }  
+    
+}
